### ISSUE TITLE
Dragonscale General

### ISSUE THREAD

**Issue by Blaeuw** [pinky39/grove#13]
In the Unflinching Assault deck, Dragonscale General's ability triggers even if it isn't on the battlefield (i.e. it happens each turn automatically). Not sure how to correct this.  Any ideas?  Thanks.

**Comment by pinky39** [comment]
Hey, yes this is missing in the triggered ability definition, if you will fix this, give me a pull request:

```
 .TriggeredAbility(p =>
        {
          // existing stuff ...

          p.TriggerOnlyIfOwningCardIsInPlay = true;
        })
```
